apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    app: nginx
  namespace: default  
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: NodePort  